### ISSUE TITLE
Windows support TODO list

### ISSUE THREAD

**Issue by jaredly** [jaredly/reason-language-server#7]
- [ ] do shell escaping on paths, so it works if there are spaces e.g. in the current directory
- [x] fix cross-file referencing (probably has to do with file-paths not lining up with URIs on windows)
- [x] make URI translation work for drives other than "C:" :P
- [ ] when doing "lookup references", references to external files are duplicated

... will add when I find things

**Comment by jaredly** [comment]
ok, windows support is lookin good
